version: "3.8"

name: laravel

volumes:
  app_files:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}
      o: bind

services:
  vite:
    build: ./docker/node
    restart: always
    ports:
      - 5173:5173
    volumes:
      - app_files:/app
    command: sh -c "npm install && exec npm run dev"

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - app_files:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/ssl:/etc/nginx/ssl
      - ./docker/nginx/logs:/var/log/nginx
    depends_on:
      - vite

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379

  php-fpm:
    build: ./docker/php
    restart: always
    ports:
      - 9000:9000
    volumes:
      - app_files:/app
    command: sh -c "composer update && exec php-fpm"
    depends_on:
      - redis
